//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GTMOAuth2SignIn.h"

@interface NIAIosSignIn : GTMOAuth2SignIn
{
}

+ (id)googleAuthorizationURL;
+ (id)nativeClientRedirectURI;
- (_Bool)cookiesChanged:(id)arg1;
- (_Bool)titleChanged:(id)arg1;
- (id)parametersForWebRequest;
- (_Bool)startSigningIn;

@end

