//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class USContentUnitViewController, USContentUnitViewControllerCache;

@protocol USContentUnitViewControllerCacheDelegate <NSObject>

@optional
- (void)cache:(USContentUnitViewControllerCache *)arg1 didRemoveController:(USContentUnitViewController *)arg2;
- (void)cache:(USContentUnitViewControllerCache *)arg1 didAddController:(USContentUnitViewController *)arg2;
@end

